FROM registry.cn-hangzhou.aliyuncs.com/okami/docker-lnmp:8.0
LABEL maintainer="陈德华 <hua@131.im>" version="1.0" license="MIT" app.name="tws"

WORKDIR /var/www/html

RUN chmod *.sh && bash /var/www/html/mongodb.sh